# FRED API Key
api_key: "f5e34adf3cdbd05efe78ad89b84087c5"

# Macroeconomic search terms (to be combined with each country)
search_terms:
  - term: "Employment"


# Countries to fetch data for
countries:
  - "USA"

# Output location for time series Excel + dictionary (relative to src/)
output_path: "excel-output/fred_macro_data.xlsx"

# Embedding model configuration
embedding:
  model: "text-embedding-3-small"

# Agent verbosity configuration
agent:
  verbose: false

# Database configuration for pgvector embedding storage
database:
database:
  type: "postgres"
  host: "localhost"
  port: 5432
  dbname: "fred_embeddings"     
  user: "postgres"               
  password: "Kanha@0410" 
